#!/bin/bash

if [ $(uname) = "Darwin" ]; then
    brew install python3
else
    sudo apt update
    sudo apt install -y python3 python3-venv python3-pip
fi

python3 -m ensurepip --upgrade
python3 -m venv username_env
source username_env/bin/activate

pip install -r requirements.txt